<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE books [
        <!ELEMENT books (book)*>
        <!ELEMENT book (title|author|character)*>
        <!ATTLIST book
                isbn CDATA #IMPLIED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT character (name|friend-of|since|qualification)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT friend-of (#PCDATA)>
        <!ELEMENT since (#PCDATA)>
        <!ELEMENT qualification (#PCDATA)>
        ]>
<books>

	<book isbn="0836217462">
		<title>
			Being a Dog Is a Full-Time Job
		</title>

		<author>Charles M. Schulz</author>

		<character>
			<name>Snoopy</name>
			<friend-of>Peppermint Patty</friend-of>
			<since>1950-10-04</since>
			<qualification> beagle </qualification>
		</character>

		<character>
			<name>Peppermint Patty</name>
			<since>1966-08-22</since>
			<qualification>bold, brash and tomboyish</qualification>
		</character>
	</book>

	<book>
		<title>
			Being a Dog Is a Full-Time Job
		</title>

		<author>Charles M. Schulz</author>

		<character>
			<name>Snoopy</name>
			<friend-of>Peppermint Patty</friend-of>
			<since>1950-10-04</since>
			<qualification>
				extroverted beagle
			</qualification>
		</character>

		<character>
			<name>Peppermint Patty</name>
			<since>1966-08-22</since>
			<qualification>bold, brash and tomboyish</qualification>
		</character>
	</book>

</books>